### PR TITLE
Modify .gitignore to ignore *.*~ backup files, also removed the *.*~ files that existed.

### PR DESCRIPTION
**Pull request by ssteinerx**

### CODE REVIEW

**Comment by radiegtya** [comment]
what is difference between this and Ssteiner x flip tree #31?

**Comment by ssteinerx** [comment]
Nothing, github doesn't seem to nail separate pull requests to particular revisions which I think it should.  Subrepositories are checkouts at specific marks, why wouldn't pull requests be?

S

**Comment by radiegtya** [comment]
ok good job @ssteinerx. But please hard retest it again from now.
I'll help when i have time.

**Comment by ssteinerx** [comment]
I'm getting a small code generation error:

   While building the application:
   lib/collections/Dogfood.js:15:4: Unexpected token ,

Investigating.  I think this might have to do with the old bug about the last blank field entry line having to be deleted manually (which is now caught by an error message, but you still have to delete the blank field manually).  I.E. it looks like the 'fix' may have introduced a new error.  I'll look right now, and post another PR when I get it fixed.

**Comment by ssteinerx** [comment]
This does not occur in the unflipped app, but mugen is generating a "," in the output as if there were a second field when only one is entered in the form.

In the unflipped version, I cannot access the new collection (which I created when NOT logged in).

**Comment by ssteinerx** [comment]
Please move my changes to a flipped branch, leaving the unflipped as the current "master", and we can continue from there.  

That will leave 'master' in a less broken state (I still think the 404 forbidden is a bug), and we can merge back when this all works.

Sorry for the trouble, I should have been more clear about merging this into a branch in the first place.

**Comment by ssteinerx** [comment]
Yes, we need to work on a branch until we both agree that it's working well.

If you'll pull over my ssteinerX-flip-tree branch into the main repo, I can send pull requests from my branch to yours and we can merge when we have both had time to test.

Steve

**Comment by radiegtya** [comment]
Your pr is ok, after I had detailed looking from your pr. I think the problem came from this file you are changing. 

private/mugen/collections/TemplateCollection.js

tomorrow I`ll check it

**Comment by ssteinerx** [comment]
You are correct.  Fixed.  It was a change I made when I moved '/private' to under mugen which makes it not 'private'.  The 'private' folder behaves differently from all other folders in Meteor and must be in the root to function properly.  I think that's a mistake and am chatting with the Meteor guys about it.

Working on a couple of other things and I'll send a new, fixed pull request in a little while.

Thanks!

Steve

**Pull request merged**
