### PR TITLE
Shell scripts to build and deploy. Normalize all configuration data in settings.json.

### PR DESCRIPTION
**Pull request by martinhbramwell**
Please see the change descriptions in [the README](https://github.com/warehouseman/meteoris/blob/master/README.md), in the wiki page "[About the command line scripts](https://github.com/warehouseman/meteoris/wiki/About-the-command-line-scripts)" and in "[Commit #9f31d7057d8b2150bd9b7bf9f6910e31ffed68d6](https://github.com/warehouseman/meteoris/commit/9f31d7057d8b2150bd9b7bf9f6910e31ffed68d6)".

### CODE REVIEW

**Comment by martinhbramwell** [comment]
Please have another look at : 
https://github.com/warehouseman/meteoris/wiki/About-the-command-line-scripts

**Comment by martinhbramwell** [comment]
Ooops.

**Comment by radiegtya** [comment]
About this, https://github.com/warehouseman/meteoris/wiki/About-the-command-line-scripts

Why don't You just simply using MUP (from arunoda) for production?

**Comment by martinhbramwell** [comment]
Mup is great.  But I have a particular server setup I do not wish to disturb.

The settings.json docs are at [About settings.json and the command line scripts](https://github.com/warehouseman/meteoris/wiki/About-settings.json-and-the-command-line-scripts)

**Comment by martinhbramwell** [comment]
?

**Comment by radiegtya** [comment]
Still to hard for me to understand the documentation without trying it in real world apps. Sadly, I do still doesn't have time to test it yet :(. Please consider to make tutorial using video tutorial if you don't mind. Btw I'll merge the code now, as it will not affect the old meteoris.

Regards

**Pull request merged**
