### PR TITLE
Add Cucumber/Velocity testing

### PR DESCRIPTION
**Pull request by martinhbramwell**
Other little changes : 
 - I noticed that some of the forms seem to be named *posts-form* even though they no longer have anything to do with the Posts collection. Cucumber needs unique naming, hence the name changes.
 - Cucumber sometimes has problems with click() but is fine submitting forms directly. So you will see event handlers for clicks replaced with event handlers for submits.
 - There's a README that confuses the package manager.  It's gone
 - There's an 'Emps' file that serves no purpose. Gone.
 - I removed quite a few console.log references that were making the Cucumber log too confusing.

### CODE REVIEW

**Comment by radiegtya** [comment]
Look Promising, I'll just try to merge it. And if there are some problem, I'll tell You.

Thanks @martinhbramwell

**Comment by martinhbramwell** [comment]
Whew!  I did not expect that.  I would feel better if you would test things first.

**Comment by radiegtya** [comment]
Ofc I have already see your whole code(although without testing it), and I think it will not interrupt the main code. So it will be fine. I am pretty sure about my skill about code scanning and skimming. LoL

**Comment by martinhbramwell** [comment]
Do you see this as a valid contribution?

Is it going where you want it to go?

**Comment by radiegtya** [comment]
I haven't familiar with cucumber, but i need those feature. When I have time, I'll deeply understanding it first then re-check your work, or maybe come with new idea. Because right now I am still focusing on building CMS built with meteoris, and other apps.

**Comment by martinhbramwell** [comment]
Yes. I understand. Testing appears to be nothing more than a cause of
delay. However, a product delivered without a serious self-test suite is
not something that will attract a large group of collaborators , or of
knowledgeable end users . Cucumber is important for developers who need to
satisfy a single customer, by showing concrete proof that their
requirements have been met

I haven't familiar with cucumber, but i need those feature. When I have
time, I'll deeply understanding it first then re-check your work, or maybe
come with new idea. Because right now I am still focusing on building CMS
built with meteoris, and other apps.

—
Reply to this email directly or view it on GitHub
<https://github.com/radiegtya/meteoris/pull/55#issuecomment-94174341>.

**Pull request merged**
