### PR TITLE
Link to preliminary copy of new doc version

### PR DESCRIPTION
**Pull request by martinhbramwell**
Please criticise the documentation heavily.

### CODE REVIEW

**Comment by martinhbramwell** [comment]
Glad you like it.

Did you see my remarks in [Trello](https://trello.com/c/RpN3pdSV/19-mugen-documentation#)?

**Comment by radiegtya** [comment]
yes, I've seen it. But I think the discussion better continues at github.
The other thing was in Your documentation, You aren't give people know where is job.name (the job object) are from, like in the google docs (which is on the collection helpers part). I think that is very important.

**Comment by martinhbramwell** [comment]
Hi  Ega

I'm not certain which bit of text you mean.

Could you paste into a reply email the text from google docs that I skipped
over?

Thanks,
Martin

**Comment by radiegtya** [comment]
in this part, please search it at google docs

```
on the above code We can clearly see that we loop through "jobs" (#each jobs). So we need a helper to get the jobs collection. Open up "client/view/employees/_form.js" and add this code.
```

**Comment by martinhbramwell** [comment]
Ok.  I have now looked at that.

I removed it from the documentation because the code is there automatically
from the code generation.  There is no code to add.

**Pull request merged**
